name: test-action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      runs: |
        using: 'node12'
        main: 'src/main.js'
# node src/action.js
# git config user.email "github action"
# git config user.name "github action"
# git config user.password ${{ secrets.GITHUB_TOKEN }}
# # git --version
# # touch test_file/test.json
# node src/main.js
# # git add test_file/test.json
# # git commit -m "test commit from action"
# # remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
# # INPUT_BRANCH=${INPUT_BRANCH:-master}
# # git push "${remote_repo}" HEAD:${INPUT_BRANCH}
        

