name: test-action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: pwd
    - name: push task
      uses: bingoYB/push-your-github@release-v1
      with:
        GITHUB_TOKEN: ${{ secrets.git_token }}
        BRANCH: master
# git config user.email "github action" 
# git config user.name "github action"
# git config user.password ${{ secrets.GITHUB_TOKEN }}
# git --version
# touch test_file/test.json
# git add test_file/test.json
# git commit -m "test commit from action"
# remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
# INPUT_BRANCH=${INPUT_BRANCH:-master}
# git push "${remote_repo}" HEAD:${INPUT_BRANCH}
        

