name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        git config user.email "github action"
        git config user.name "github action"
        git config user.password ${{ secrets.GITHUB_TOKEN }}
        git --version
        touch test_file/test.json
        ls
        git add test_file/test.json
        git commit -m "test commit from action"
        git push https:// master${{ secrets.GITHUB_TOKEN }}@github.com/test_my_action.git master
        

